In [4]:
import numpy as np

# Numpy_Assignment_2 (Zohaib PIAIC146343)

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
a=np.arange(10)
print(a)

a.reshape(2,5)


[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [20]:
a= np.arange(10).reshape(2,5)
b= np.array([[1,1,1,1,1],[1,1,1,1,1]])
c=np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [49]:
a= np.arange(10).reshape(2,5)
b= np.array([[1,1,1,1,1],[1,1,1,1,1]])
c=np.hstack((a,b))
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [24]:
a= np.arange(10).reshape(2,5)
print(a)
array_1d = a.flatten()
array_1d 

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [52]:
a= np.arange(15).reshape(5,3)

print(a)

b=a.flatten()
b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [26]:
a= np.arange(15)
print(a)
b=a.reshape(5,3)
b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [33]:
a= np.arange(25).reshape(5,5)
print(a)
b = a** 2
b


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [35]:
a= np.arange(30).reshape(5,6)
print(a)
b = np.mean(a)
b


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [37]:
b = np.std(a)
b

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [38]:
b = np.median(a)
b

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [39]:
b = a.T
b

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [55]:
a= np.arange(16).reshape(4,4)
print(a)
b = np.trace(a)
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [58]:
print(a)
from numpy.linalg import det 
b=np.linalg.det(a)
b


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [62]:
a= np.arange(16)
print(a)
b=np.percentile(a, 5)
print(b)
c=np.percentile(a, 95)
c


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
0.75


14.25

## Question:15

### How to find if a given array has any null values?

In [63]:
arr = np.array([1,2,3,4,5,6,7,np.NaN])
x = np.argwhere(np.isnan(arr))
print("Null value at Index:",x)

Null value at Index: [[7]]
